MyLibrabry/Controllers/BasicAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyLibrabry.Models;
namespace MyLibrabry.Controllers
{
    public class BasicAdminController : Controller
    {
        // GET: BasicAdmin
        public ActionResult Index()
        {
            int id = int.Parse(Session["u_id"].ToString());
            Users u = UserBL.getById(id);
            return View(u);
        }
        public ActionResult AdminIndex()
        {

            return View(UserBL.GetAllAdmin());
        }

        [HttpGet]
        public ViewResult CreateAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateAdmin(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.InsertAdmin(u);
                return RedirectToAction("AdminIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ViewResult EditAdmin(int id)
        {
            var u = UserBL.GetById(id);
            return View(u);
        }


        [HttpPost]
        public ActionResult EditAdmin(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.Update(u);
                return RedirectToAction("AdminIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteAdmin(int id)
        {
            UserBL.Delete(id);
            return RedirectToAction("AdminIndex");
        }



        public ActionResult EmployeeIndex()
        {
            return View(UserBL.GetAllEmp());
        }

        [HttpGet]
        public ViewResult CreateEmployee()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateEmployee(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.InsertEmp(u);
                return RedirectToAction("EmployeeIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ViewResult EditEmployee(int id)
        {
            var u = UserBL.GetById(id);
            return View(u);
        }


        [HttpPost]
        public ActionResult EditEmployee(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.Update(u);
                return RedirectToAction("EmployeeIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteEmployee(int id)
        {
            UserBL.Delete(id);
            return RedirectToAction("EmployeeIndex");
        }



        public ActionResult MemberIndex()
        {
            return View(UserBL.GetAllMem());
        }

        [HttpGet]
        public ViewResult CreateMember()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateMember(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.InsertMemb(u);
                return RedirectToAction("MemberIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ViewResult EditMember(int id)
        {
            var u = UserBL.GetById(id);
            return View(u);
        }


        [HttpPost]
        public ActionResult EditMember(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.Update(u);
                return RedirectToAction("MemberIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteMember(int id)
        {
            UserBL.Delete(id);
            return RedirectToAction("MemberIndex");
        }

        //BOOOK

        [HttpGet]
        public ActionResult BookB()
        {
            return View(BookBL.GetAll());


        }

        [HttpGet]
        public ViewResult CreateBook()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateBook(Book u)
        {
            if (ModelState.IsValid)
            {
                BookBL.Insert(u);
                return RedirectToAction("BookB");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ViewResult EditBook(int id)
        {
            var u = BookBL.GetById(id);
            return View(u);
        }


        [HttpPost]
        public ActionResult EditBook(Book u)
        {
            if (ModelState.IsValid)
            {
                BookBL.Update(u);
                return RedirectToAction("BookB");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]

        public ActionResult DeleteBook(int id)
        {
            UserBL.Delete(id);
            return RedirectToAction("BookB");
        }


    }

}

MyLibrabry/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyLibrabry.Models;
namespace MyLibrabry.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MemberIndex()
        {
            return View(UserBL.GetAllMem());
        }

        [HttpGet]
        public ViewResult CreateMember()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateMember(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.InsertMemb(u);
                return RedirectToAction("MemberIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ViewResult EditMember(int id)
        {
            var u = UserBL.GetById(id);
            return View(u);
        }


        [HttpPost]
        public ActionResult EditMember(Users u)
        {
            if (ModelState.IsValid)
            {
                UserBL.Update(u);
                return RedirectToAction("MemberIndex");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteMember(int id)
        {
            UserBL.Delete(id);
            return RedirectToAction("MemberIndex");
        }
    }
}

MyLibrabry/Controllers/userloginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyLibrabry.Models;

namespace MyLibrabry.Controllers
{
    public class userloginController : Controller
    {
        // GET: userlogin
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Users lc)

        {
            if (UserBL.checkIn(lc.u_name, lc.u_password) == true)
            {
                if (UserBL.getType(lc.u_name) == "B")
                {
                    Session.Add("u_id", UserBL.GetId(lc.u_name));

                    return RedirectToAction("Index", "BasicAdmin");
                }
                else if (UserBL.getType(lc.u_name) == "A")
                {
                    Session.Add("u_id", UserBL.GetId(lc.u_name));
                    return RedirectToAction("Index", "Admin");
             
                }
                else if (UserBL.getType(lc.u_name) == "E")
                {
                    Session.Add("u_id", UserBL.GetId(lc.u_name));

                    return RedirectToAction("Index","Employee");
                }
                else if (UserBL.getType(lc.u_name) == "M")
                {
                    Session.Add("u_id", UserBL.GetId(lc.u_name));

                    return RedirectToAction("Index", "Member");
                }
              


            }

            return View();
        }
    }
}

MyLibrabry/Views/BasicAdmin/AdminIndex.cshtml
@model IEnumerable<MyLibrabry.Models.Users>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMP.cshtml";
}

<h2>Index</h2>

<a href="/BasicAdmin/CreateAdmin" class="btn btn-primary">Create One</a>

<br />
<hr />
<br />
<div class="form-group">
    <div class="input-group">
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">

    </div>
</div>
<script>
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>
<table id="myTable" class="table table-active table-bordered  table-striped ">
    <tr>
        @*<th> @Html.DisplayNameFor(ww => ww.u_id) </th>*@
        <th>@Html.DisplayNameFor(ww => ww.u_fname) </th>
        <th> @Html.DisplayNameFor(ww => ww.u_lname) </th>
        <th> @Html.DisplayNameFor(ww => ww.hdate) </th>
        <th> @Html.DisplayNameFor(ww => ww.salary) </th>
        <th> @Html.DisplayNameFor(ww => ww.age) </ th >
        <th> @Html.DisplayNameFor(ww => ww.u_address) </th>
        <th> @Html.DisplayNameFor(ww => ww.phone) </th>
        <th>@Html.DisplayNameFor(ww => ww.u_email) </th>
        <th>@Html.DisplayNameFor(ww => ww.photo) </th>


        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                @Html.DisplayFor(ww => item.u_id)
            </td>*@
            <td>
                @Html.DisplayFor(ww => item.u_fname)
            </td>
            <td>
                @Html.DisplayFor(ww => item.u_lname)
            </td>
            <td>
                @Html.DisplayFor(ww => item.hdate)
            </td>
            <td>
                @Html.DisplayFor(ww => item.salary)
            </td>
            <td>
                @Html.DisplayFor(ww => item.age)
            </td>
            <td>
                @Html.DisplayFor(ww => item.u_address)
            </td>
            <td>
                @Html.DisplayFor(ww => item.phone)
            </td>
            <td>
                @Html.DisplayFor(ww => item.u_email)
            </td>
            <td>

                <img class="img" src="~/LayoutMP/photo/@item.photo" />
            </td>

            <td>
                <pre> @Html.ActionLink("Edit","EditAdmin","BasicAdmin",new {id=item.u_id  },new {@class="btn btn-success" }) | @Html.ActionLink("Delete","DeleteAdmin", "BasicAdmin", new {id=item.u_id },new {@class="btn btn-danger",onclick="return confirm('Are u Sure!!!')" })</pre>
            </td>
        </tr>
    }
</table>

MyLibrabry/Views/BasicAdmin/BookB.cshtml
@model IEnumerable<MyLibrabry.Models.Book>

@{
    ViewBag.Title = "BookEmp";
    Layout = "~/Views/Shared/_LayoutMP.cshtml";
}

<h2>BookEmp</h2>

<a href="/BasicAdmin/CreateBook" class="btn btn-primary">Create One</a>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.b_title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.b_author)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.edition)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.no_shelf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.no_copies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.no_pages)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.photo)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.b_title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.b_author)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.edition)
            </td>

            @*<td>
                    @Html.DisplayFor(modelItem => item.avilable)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.no_shelf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.no_copies)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.no_pages)
            </td>
            <td>
                <img src="~/LayoutMP/bookimg/@item.photo" class="img"/>
            </td>
           

            <td>
                @Html.ActionLink("Edit", "EditBook", "BasicAdmin", htmlAttributes: new { @class = "btn btn-success" }, routeValues: new { id = item.b_id }) |
                
                @Html.ActionLink("Delete", "DeleteBook", "BasicAdmin", htmlAttributes: new { @class = "btn btn-danger" }, routeValues: new { id = item.b_id })

            </td>

        </tr>
    }

</table>

MyLibrabry/Views/BasicAdmin/CreateAdmin.cshtml
@model MyLibrabry.Models.Users
@{
    ViewBag.Title = "CreateAdmin";
    Layout = "~/Views/Shared/_LayoutMP.cshtml";
}

<span data-icon="" class="icon"> Add Admain</span>

@using (Html.BeginForm("CreateAdmin", "BasicAdmin", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_fname, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_fname, new { htmlAttributes = new { @class = "form-control" } })
            @* @Html.TextBoxFor(ww => ww.Id, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_fname)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_lname, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_lname, new { htmlAttributes = new { @class = "form-control" } })
            @* @Html.TextBoxFor(ww => ww.Id, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_lname)
        </div>
    </div>


    <div class="form-group row">
        @Html.LabelFor(ww => ww.hdate, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.hdate, new { htmlAttributes = new { @class = "form-control" } })
            @* @Html.TextBoxFor(ww => ww.Id, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.hdate)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.salary, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.salary, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Salary, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.salary)
        </div>
    </div>


    <div class="form-group row">
        @Html.LabelFor(ww => ww.age, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.age, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Age, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.age)
        </div>
    </div>


    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_address, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_address, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Location, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_address)
        </div>
    </div>


    <div class="form-group row">
        @Html.LabelFor(ww => ww.phone, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.phone, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Salary, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.phone)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_name, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_name, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Salary, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_name)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_password, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_password, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Pwd, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_password)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.Confpwd, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.Confpwd, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Confpwd, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.Confpwd)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_email, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_email, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.TextBoxFor(ww => ww.Email, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_email)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.photo, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.photo, new { htmlAttributes = new { @class = "form-control" } })
            @* @Html.TextBoxFor(ww => ww.Id, new { @class = "form-control" })*@
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.photo)
        </div>
    </div>


    <input type="submit" value="CreateAdmin" class="btn btn-primary" />

}

MyLibrabry/Views/BasicAdmin/EmployeeIndex.cshtml
@model IEnumerable<MyLibrabry.Models.Users>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMP.cshtml";
}

<h2>Index</h2>

<a href="/BasicAdmin/CreateEmployee" class="btn btn-primary">Create One</a>

<br />
<hr />
<br />

<table class="table table-active table-bordered  table-striped ">
    <tr>
        <th> @Html.DisplayNameFor(ww => ww.u_id) </th>
        <th>@Html.DisplayNameFor(ww => ww.u_fname) </th>
        <th> @Html.DisplayNameFor(ww => ww.u_lname) </th>
        <th> @Html.DisplayNameFor(ww => ww.hdate) </th>
        <th> @Html.DisplayNameFor(ww => ww.salary) </th>
        <th> @Html.DisplayNameFor(ww => ww.age) </ th >
        <th> @Html.DisplayNameFor(ww => ww.u_address) </th>
        <th> @Html.DisplayNameFor(ww => ww.phone) </th>
        <th>@Html.DisplayNameFor(ww => ww.u_email) </th>
        <th>@Html.DisplayNameFor(ww => ww.photo) </th>


        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(ww => item.u_id)
            </td>
            <td>
                @Html.DisplayFor(ww => item.u_fname)
            </td>
            <td>
                @Html.DisplayFor(ww => item.u_lname)
            </td>
            <td>
                @Html.DisplayFor(ww => item.hdate)
            </td>
            <td>
                @Html.DisplayFor(ww => item.salary)
            </td>
            <td>
                @Html.DisplayFor(ww => item.age)
            </td>
            <td>
                @Html.DisplayFor(ww => item.u_address)
            </td>
            <td>
                @Html.DisplayFor(ww => item.phone)
            </td>
            <td>
                @Html.DisplayFor(ww => item.u_email)
            </td>
            <td>

                <img class="img" src="~/LayoutMP/photo/@item.photo" />
            </td>

            <td>
                <pre> @Html.ActionLink("Edit","EditEmployee","BasicAdmin",new {id=item.u_id  },new {@class="btn btn-success" }) | @Html.ActionLink("Delete","DeleteEmployee", "BasicAdmin", new {id=item.u_id },new {@class="btn btn-danger",onclick="return confirm('Are u Sure!!!')" })</pre>
            </td>
        </tr>
    }
</table>

MyLibrabry/Views/BasicAdmin/Index.cshtml
@model MyLibrabry.Models.Users
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutProfile.cshtml";
}

<h2>Index</h2>

@section scripts
{


    <img id="blah" src="~/LayoutProfile/images/Alaa.jpg" alt="your image" class="rounded" />
    <input type='file' onchange="readURL(this);" />
    <script>
                    function readURL(input) {
                        if (input.files && input.files[0]) {
                            var reader = new FileReader();

                            reader.onload = function (e) {
                                $('#blah')
                                    .attr('src', e.target.result)
                                    .width(150)
                                    .height(200);
                            };

                            reader.readAsDataURL(input.files[0]);
                        }
                    }
    </script>

     
<br />
<br />
<br />
<div class="send-button w3layouts agileits">
    <form>
        <a href="/BasicAdmin/AdminIndex" class="btn btn-primary">Admin</a>
        <br />
        <a href="/BasicAdmin/EmployeeIndex" class="btn btn-primary">Employee</a>
        <br />
        <a href="/BasicAdmin/MemberIndex" class="btn btn-primary">Member</a>
        <br />
        <a href="/BasicAdmin/BookB" class="btn btn-primary">Book</a>
        <br />
       
    </form>
</div>
<div class="clear"></div>
        

<div class="clear"></div>
 }
@using (Html.BeginForm("Index", "BasicAdmin", FormMethod.Post))
{


    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_fname, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_fname, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_fname)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_lname, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_lname, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_lname)
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(ww => ww.hdate, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.hdate, new { htmlAttributes = new { @class = "form-control" } })

            @Html.HiddenFor(ww => ww.hdate)
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.hdate)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.salary, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.salary, new { htmlAttributes = new { @class = "form-control" } })

            @Html.HiddenFor(ww => ww.salary)
        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.salary)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.age, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.age, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.age)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_address, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_address, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_address)
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(ww => ww.phone, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.phone, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.phone)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_name, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_name, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_name)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_password, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_password, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_password)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.Confpwd, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.Confpwd, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.Confpwd)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.u_email, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.u_email, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">
            @Html.ValidationMessageFor(ww => ww.u_email)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(ww => ww.photo, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.EditorFor(ww => ww.photo, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="col-sm-10">

        </div>
    </div>

    @Html.ActionLink("Edit", "EditIndex", "BasicAdmin", htmlAttributes: new { @class = "btn btn-success" }, routeValues: new { id = Model.u_id })
    <br>
    <br>
    @Html.ActionLink("LOG OUT", "Index", "userlogin", htmlAttributes: new { @class = "btn btn-success" }, routeValues: new { id = Model.u_id })

}

@section who
{
    <h2>Basic Admin</h2>
  }